controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - alpha/joint1
      - alpha/joint2
      - alpha/joint3
      - alpha/joint4
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - alpha/joint5
      - alpha/joint6
  - name: fake_vehicle_controller
    type: $(arg execution_type)
    joints:
      - x_displacement
      - y_displacement
      - z_displacement
      - yaw_displacement
  - name: fake_vehicle_arm_controller
    type: $(arg execution_type)
    joints:
      - x_displacement
      - y_displacement
      - z_displacement
      - yaw_displacement
      - alpha/joint1
      - alpha/joint2
      - alpha/joint3
      - alpha/joint4
initial:  # Define initial robot poses.
  - group: arm
    pose: home_arm
  - group: vehicle_arm
    pose: home