controller_list:
  - name: fake_Arm_controller
    type: $(arg execution_type)
    joints:
      - seabotix/alpha/joint1
      - seabotix/alpha/joint2
      - seabotix/alpha/joint3
      - seabotix/alpha/joint4
  - name: fake_Gripper_controller
    type: $(arg execution_type)
    joints:
      - seabotix/alpha/joint5
      - seabotix/alpha/joint6
initial:  # Define initial robot poses.
#  - group: Arm
#    pose: home

  []