# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: vehicle_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - x_displacement
    - y_displacement
    - z_displacement
    - yaw_displacement
    - alpha/anchor
    - alpha/joint1
    - alpha/joint2
    - alpha/joint3
    - alpha/joint4
    - alpha/joint5
    - alpha/joint6
    - seabotix/camera_joint
    - seabotix/camera_optical_joint
    - seabotix/dvl_joint
    - seabotix/dvl_sonar0_joint
    - seabotix/dvl_sonar1_joint
    - seabotix/dvl_sonar2_joint
    - seabotix/dvl_sonar3_joint
    - seabotix/gps_joint
    - seabotix/imu_joint
    - seabotix/magnetometer_joint
    - seabotix/pose_sensor_default_joint
    - seabotix/pressure_joint
    - seabotix/rpt_joint
    - seabotix/thruster_0_joint
    - seabotix/thruster_1_joint
    - seabotix/thruster_2_joint
    - seabotix/thruster_3_joint
    - seabotix/thruster_4_joint
    - seabotix/thruster_5_joint
    - seabotix_forward_sonardown_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - alpha/joint1
      - alpha/joint2
      - alpha/joint3
      - alpha/joint4
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - alpha/joint5
      - alpha/joint6
  - name: vehicle_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - x_displacement
      - y_displacement
      - z_displacement
      - yaw_displacement
  - name: vehicle_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - x_displacement
      - y_displacement
      - z_displacement
      - yaw_displacement
      - alpha/joint1
      - alpha/joint2
      - alpha/joint3
      - alpha/joint4