# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: vehicle_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - x_displacement
    - y_displacement
    - z_displacement
    - yaw_displacement
    - alpha/joint1
    - alpha/joint2
    - alpha/joint3
    - alpha/joint4
    - alpha/joint5
    - alpha/joint6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: seabotix/alpha/arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - alpha/joint1
      - alpha/joint2
      - alpha/joint3
      - alpha/joint4
  - name: seabotix/alpha/gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - alpha/joint5
      - alpha/joint6
  - name: seabotix/alpha/vehicle_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - x_displacement
      - y_displacement
      - z_displacement
      - yaw_displacement
  # - name: vehicle_arm_controller
  #   action_ns: follow_joint_trajectory
  #   default: True
  #   type: FollowJointTrajectory
  #   joints:
  #     - x_displacement
  #     - y_displacement
  #     - z_displacement
  #     - yaw_displacement
  #     - alpha/joint1
  #     - alpha/joint2
  #     - alpha/joint3
  #     - alpha/joint4